## Prace przy modelu uczenia maszynowego

In [1]:
# importy danych
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
import os
from dotenv import load_dotenv
from pathlib import Path

# pobranie zmiennych env
load_dotenv()
test_size = float(os.getenv("TEST_SIZE"))
random_seed = int(os.getenv("RANDOM_SEED"))
output_dir = Path(os.getenv("REPORT_PATH"))
output_dir.mkdir(parents=True, exist_ok=True)

In [2]:
# zapisanie danych w dataframe
data = load_iris(as_frame=True)
iris_features = data.data
iris_target = data.target

# wyświetlenie podstawowych informacji o zbiorze
display(iris_features.head())
print(f"\nRozmiar wybranego zbioru: {iris_features.shape[0]}x{iris_features.shape[1]}\n")
display(iris_features.describe())

print(f"Klasy w zbiorze: {iris_target.unique()}")

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

Rozmiar wybranego zbioru: 150x4

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

Klasy w zbiorze: [0 1 2]

In [3]:
# podział danych na zbiory treningowy i testowy
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_features, iris_target, test_size=test_size, random_state=random_seed)

In [4]:
# wykorzystanie drzewa decyzyjnego
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

y_preds = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_preds)
print("Jakość predykcji: ", accuracy)
print("\nWypisanie raportu:")
print(classification_report(y_test, y_preds))

Jakość predykcji:  1.0

Wypisanie raportu:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [5]:
# zapisanie classification_report do pliku .txt
report = classification_report(y_test, y_preds)

(output_dir / "report_card.txt").write_text(
    report,
    encoding="utf-8"
)

380